### PR TITLE
Added wordpress-server-block.conf file to fix issue WordPress not starting

### PR DESCRIPTION
**Pull request by Remzi1993**
I only added the wordpress-server-block.conf file to fix issue #9
It seems like this file is required.

### CODE REVIEW

**Comment by andresbono** [comment]
Thanks for submitting this PR. Would you mind modifying the README.md so it indicates how to download this required file?

**Comment by Remzi1993** [comment]
> Thanks for submitting this PR. Would you mind modifying the README.md so it indicates how to download this required file?
> 
> * https://github.com/bitnami/bitnami-docker-wordpress-nginx/blame/fef51319f64dde8e6fa1ea042128365ba0916c3c/README.md#L14
> * https://github.com/bitnami/bitnami-docker-wordpress-nginx/blame/fef51319f64dde8e6fa1ea042128365ba0916c3c/README.md#L66

Devs shouldn't need to download an additional file, it should just work with git clone.
`git clone git@github.com:bitnami/bitnami-docker-wordpress-nginx.git` and cd into the directory and after that `docker-compose up -d`

**Comment by carrodher** [comment]
Now the config file is in the root directory so the docker-compose works out of the box. In the same way, we created a task to think in a long-term solution as we need to integrate this file (the one in the root folder) into our automated releases pipeline.

**Comment by Remzi1993** [comment]
@carrodher Thanks for merging! Good luck with the task, I don't know if I'm able to help you guys with that. I'm always willing to assist.

**Comment by carrodher** [comment]
Thanks for the PR, the pending stuff is something internal but thanks anyway for the offer!

**Pull request merged**
