### PR TITLE
see #69: allow uses to customize keys and salts

### PR DESCRIPTION
**Pull request by ziodave**
**Description**

Users will be able to configure the keys and salts by using environment variables similar to what the official WordPress image does (`-e WORDPRESS_AUTH_KEY=...`, `-e WORDPRESS_SECURE_AUTH_KEY=...`, `-e WORDPRESS_LOGGED_IN_KEY=...`, `-e WORDPRESS_NONCE_KEY=...`, `-e WORDPRESS_AUTH_SALT=...`, `-e WORDPRESS_SECURE_AUTH_SALT=...`, `-e WORDPRESS_LOGGED_IN_SALT=...`, `-e WORDPRESS_NONCE_SALT=...`).

**Benefits**

Users will be able to start up multiple instances of the same WordPress configuration without causing invalidation of salts.

**Possible drawbacks**

None known.

**Applicable issues**

- Fixes https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/69

**Additional information**

Sponsored by [WordLift](https://wordlift.io).

### CODE REVIEW

**Comment by Mauraza** [comment]
Hi @ziodave,

Thanks for the PR!, let me run some tests, I will update the thread with more information!

**Review by Mauraza — CHANGES_REQUESTED** [review]
Hi @ziodave,

You need to add the new variable in https://github.com/bitnami/bitnami-docker-wordpress-nginx/blob/master/5/debian-10/rootfs/opt/bitnami/scripts/wordpress-env.sh

**Comment by ziodave** [comment]
@Mauraza I applied the requested changes. Cheers.

**Comment by Mauraza** [comment]
Hi @ziodave,

Thanks for implementing the request changes! I finish some internal review and I will update this thread when I have more information.

**Review by Mauraza — APPROVED** [review]
LGTM!!

**Comment by Mauraza** [comment]
Hi @ziodave,

Thanks again for the contribution!!

**Pull request merged**
